services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql_admin
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  demo_project13:
    image: vdanilintest/demo_project13:v1.0.0
    container_name: demo_project13
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:psql_admin@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data: