name: project13 CI/CD

env:
  PYTHONPATH: ${{ github.workspace }}/demo_project13

on:
  push:
    branches: [ main, dev, 'feature/**' ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests

  prepare-main-dev:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: LogIn to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push DockerImage
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo_project13:v1.0.0

  deploy-main-dev:
    needs: prepare-main-dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'

    steps:
      - name: Install SSH Client
        run: |
          sudo apt-get update
          sudo sudo apt-get install -y sshpass openssh-client

      - name: Setup SSH
        env:
          ORACLE_IP: ${{ secrets.ORACLE_IP }}
          ORACLE_SSHKEY: ${{ secrets.ORACLE_SSHKEY }}
        run: |
          mkdir -p ~/.ssh
          cat << 'EOF' > ~/.ssh/id_rsa
          $ORACLE_SSHKEY
          EOF
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $ORACLE_IP >> ~/.ssh/known_hosts

      - name: app deploy
        env:
          ORACLE_HOST: ${{ secrets.ORACLE_HOST }}
          ORACLE_SSHKEY: ${{ secrets.ORACLE_SSHKEY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run:
          ssh $ORACLE_HOST "
            ./setup.sh
            docker stop demo_project13 || true &&
            docker rm demo_project13 || true &&
            docker pull $DOCKERHUB_USERNAME/demo_project13:v1.0.0 &&
            docker run -d --name demo_project13 -p 5000:5000 $DOCKERHUB_USERNAME/demo_project13:v1.0.0
          "

  deploy-feature:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature/')

    steps:
      - name: Success
        run: echo 'project13 tested'