name: project13 deploy schema

env:
  PYTHONPATH: ${{ github.workspace }}/demo_project13

on:
  push:
    branches: [ main, dev, 'feature/**' ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests

  deploy-main-dev:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run server
        run: echo "project13 tested and installed"

  deploy-feature:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature/')

    steps:
      - name: Success
        run: echo 'project13 tested'